services:
  frontend:
    build: 
      context: ./portfolio-frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=https://yasinnerten.com/api 
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio-network
    deploy:
      resources:
        limits:
          memory: "350M"
          cpus: "0.45"


  backend:
    build: ./portfolio-backend
    expose:
      - "8080"
    volumes:
      - ./portfolio-backend/static:/root/static
      - ./portfolio-backend/db:/root/db
    environment:
      - PORT=8080
      - DB_PATH=/root/db/portfolio.db
      - APP_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio-network
    deploy:
      resources:
        limits:
          memory: "230M"
          cpus: "0.25"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl  # Simple directory for your SSL files
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network
    restart: always
    deploy:
      resources:
        limits:
          memory: "170M"
          cpus: "0.15"

volumes:
  db-data:

networks:
  portfolio-network:
    driver: bridge 